name: pritt_server
description: The Pritt Server used for serving Pritt
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.5.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  env:
    path: "../packages/env"
  path: ^1.9.0
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
