name: dart_functions
description: A starting point for developing serverless functions with Dart.
version: 1.0.0

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
