name: env_example
description: A sample of using/implementing the env package.

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  env: 
    path: ..

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0
